test_csv:

features_root_dir:
output_dir: 'output/debug'
experiment_name: 'inference'
level: 'global'

task: 'classification'
loss: 'ce'

num_classes: 2
label_name: 'label'
label_mapping:
label_encoding:

model:
  checkpoint:
  dropout: 0.25
  embed_dim_patch: 384
  embed_dim_region: 192
  embed_dim_slide: 192
  region_size: 4096
  patch_size: 256
  mini_patch_size: 16
  agg_method: 'concat'
  slide_pos_embed:
    use: False
    learned:
    type:
    max_seq_len:
    max_nslide:
    tile_size:

speed:
  num_workers: 8

wandb:
  enable: False
  project: 'hipt'
  username: 'clemsg'
  exp_name: '${experiment_name}'
  tags:
  dir: '/home/user'
  to_log:
    - 'test': ['auc', 'kappa', 'cm']
  group:
  resume_id:

hydra:
  run:
    dir: /tmp/hydra_output