test_csv:

features_dir:
output_dir: 'output/debug'
experiment_name: 'inference'
level: 'global'

task: 'survival'

label_name: 'label'
label_mapping:
label_encoding:
nbins:

model:
  checkpoint:
  dropout: 0.25
  embed_dim_patch: 384
  embed_dim_region: 192
  region_size: 4096
  patch_size: 256
  mini_patch_size: 16
  agg_method: 'concat'
  slide_pos_embed:
    use: False
    learned:
    type:
    max_seq_len:
    max_nslide:
    tile_size:

wandb:
  enable: False
  project: 'hipt'
  username: 'clemsg'
  exp_name: '${experiment_name}'
  tags:
  dir: '/home/user'
  to_log:
    - 'train': ['loss', 'c-index']
    - 'tune': ['loss', 'c-index']
    - 'test': ['c-index']
  group:
  resume_id:

hydra:
  run:
    dir: /tmp/hydra_output